# Generated by Django 5.0.4 on 2024-05-07 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0002_remove_product_cat_alter_product_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cat',
            field=models.IntegerField(default=0, verbose_name='Category'),
            preserve_default=False,
        ),
    ]
